### ISSUE TITLE
Wrong configuration for Disqus

### ISSUE THREAD

**Issue by DjLeChuck** [MunifTanjim/minimo#123]
Hi,

First, thank you for you theme, it's simple and perfect! 👍 

There is a bug with Discus configuration. [In the example `toml` file](https://github.com/MunifTanjim/minimo/blob/master/exampleSite/config.toml#L8) you are using `disqusShortname` but [in the partial](https://github.com/MunifTanjim/minimo/blob/master/layouts/partials/entry/comments.html#L14) you use `.Site.DisqusShortname` so the parameter which start by a lower letter does not match the one with an upper.

EDIT: [My PR](https://github.com/MunifTanjim/minimo/pull/124) to close this issue!

**Comment by MunifTanjim** [comment]
Are you sure this is even an issue?

Set the `disqusShortname` to your Disqus shortname in your `config.toml` file. And try to build your site.

- Is the build successful?
- Is Disqus comment present in the rendered site?

If answer to the both question is "YES", then this is not an issue. @DjLeChuck

**Comment by DjLeChuck** [comment]
Yes, I think there is an issue. :)

In the toml file, the parameter name is `disqusShortname`.
In the `comments.html` file, the parameter name is `DisqusShortname`.

If I use `disqusShortname` in my `config.toml` Discus is not present but if I use  `DisqusShortname` he is.
In both case my site builds with success. The error I mention in my PR is with your CI: https://app.netlify.com/sites/minimo/deploys/5ad22cb782d3f15d458335ae

Sorry if I'm not clear...

**Comment by MunifTanjim** [comment]
These two lines should make it clear:

https://github.com/gohugoio/hugo/blob/a4deaeff0cfd70abfbefa6d40c0b86839a216f6d/hugolib/site.go#L1120

- In the `config.toml` file, `disqusShortname` is specified.

https://github.com/gohugoio/hugo/blob/a4deaeff0cfd70abfbefa6d40c0b86839a216f6d/hugolib/site.go#L374

- And in the templates, it is accessed by `.Site.DisqusShortname`.

So, that error in your PR is the expected behavior. And it is caused by your commit in the PR.

---

> If I use `disqusShortname` in my config.toml Discus is not present but if I use `DisqusShortname` he is.

That should not be the case. If that happens, that means Hugo is doing something unexpected.

Can you give me some more information about your system?
- Hugo version
- Operating System

**Comment by DjLeChuck** [comment]
Ok sorry I was not aware about this, thank you for the two lines!

After a double check, all is good... I think it was a cache issue with firebase. Sorry for the false issue and for taking your time!
