### ISSUE TITLE
Feature Request:Nesting menus

### ISSUE THREAD

**Issue by idevz** [MunifTanjim/minimo#13]
I found that minimo didn't support nesting menus right now, did this will support some day?

**Comment by idevz** [comment]
got it, I didn't have any idea right now, and thanks so much.

**Comment by HorribleGeek** [comment]
Hey! Maybe we can shift the menu to the sidebar?

**Comment by MunifTanjim** [comment]
That can definitely be an option. If you are up for doing that, you're welcomed to create a PR when you're done.

By the way, you'll have to keep _accessibility_ in mind when implementing the design, so that people who uses screen-readers to navigate the website don't face any problems.

@HorribleGeek

**Comment by mastersilv3r** [comment]
I love Minimo theme but now got stuck with nested menu implementation. I really need it and don't know much html/css. I believe the theme will be more complete with the feature. It is a serious limitation. Will appreciate any help!

**Comment by MunifTanjim** [comment]
A draft implementation can be found at 01cf5e4b503d3a19bcc2e0a574ab42872afad810 in the [nested-menu](https://github.com/MunifTanjim/minimo/tree/nested-menu) branch.

Demo site: https://nested-menu--minimo.netlify.com

But, I won't be merging it to the master branch, because the implementation is too complicated and buggy. So, it defeats the purpose of Minimo as a minimal theme.

For the time being, I'm closing this issue.

**Comment by jdittrich** [comment]
I could provide a PR for a nested sidebar menu. This is how it would look like:

![image](https://user-images.githubusercontent.com/3416487/40278676-18637a42-5c36-11e8-846c-7cd07750f3de.png)

The DOM would be a list in a list item. 

@MunifTanjim – shall I clean up the code and create a PR?

**Comment by MunifTanjim** [comment]
@jdittrich Yeah, why not :smiley:
