### ISSUE TITLE
Emacs Org mode support for author

### ISSUE THREAD

**Issue by measpear** [MunifTanjim/minimo#142]
Hi,

I tried your theme with ox-hugo and works well with the taxonomy authors. By following the Author Guide, I can add multiple authors for the site. 

However when I use the basic org mode file for the post with #+AUTHOR: measpear I can not see the author info at the top of the post between date and reading time info. 

Could you add the support for org-mode +AUTHOR property ?

**Comment by MunifTanjim** [comment]
Related to missing support for custom taxonomies in `goorgeous`.

Issue: chaseadamsio/goorgeous#88

**Comment by kaushalmodi** [comment]
@measpear `ox-hugo` generates a list parameter named `author` by default as the inbuild Org keyword is singular too: `#+AUTHOR:` or `:EXPORT_AUTHOR` as a property.

.. you can change that i.e. have it generate `authors` instead of `author` to fit this theme. 

- [Commit that I just added to the `ox-hugo` test suite to cover this usage][1]
- [Generated Markdown][2]
- [Hugo generated HTML][3] (*using the `hugo-bare-min-theme`*)

*The test case I added uses the subtree-based flow. But you can do the same for file-based flow too, if that's what you prefer.*

See https://ox-hugo.scripter.co/doc/replace-front-matter-keys/ for more info.

[1]: https://ox-hugo.scripter.co/test/posts/plural-author-front-matter/
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/plural-author-front-matter.md
[3]: https://ox-hugo.scripter.co/test/posts/plural-author-front-matter/
