### ISSUE TITLE
Prevent automatic title-case for tags

### ISSUE THREAD

**Issue by jas-ho** [MunifTanjim/minimo#169]
Hi,
first of all: Thanks a lot for your work on this beautiful theme!

I have a question regarding automatic case conversion for tags: **I would like to keep the case of my tags as provided**, i.e. if I have a tag `"about"` in the front matter of a post, I would like it to show up as `"about"` in the tag-cloud. In my case, it seems to always come out as `"About"`. Is there a setting which I can use to prevent this?

Also: What do I have to do to make the title of the tag-cloud read `"tags"` (lower case) instead of `"Tags"` (title case)?

Thanks for your help!
Cheers
Jason

**Comment by MunifTanjim** [comment]
related to: #77 (read that thread first, then come back here to read this comment)

---

> I have a question regarding automatic case conversion for tags: I would like to keep the case of my tags as provided, i.e. if I have a tag "about" in the front matter of a post, I would like it to show up as "about" in the tag-cloud. In my case, it seems to always come out as "About". Is there a setting which I can use to prevent this?

Either you set the tag as: `tags = ["some-tag"]` and create a file `/content/tags/some-tag/_index.md` with the frontmatter `title: some-Tag-WITH-wHaTeVeR-case-you-wanT`

Or, you will have to override the `/layouts/partials/extras/taxonomy_cloud.html` file with your necessary adjustments.

https://github.com/MunifTanjim/minimo/blob/9db19f947a2571801b8e03cb97c6b7fa91c90506/layouts/partials/extras/taxonomy_cloud.html#L29-L35

( Your issue occurs because the `.Title` variable is automatically capitalized by Hugo. )

---

> Also: What do I have to do to make the title of the tag-cloud read "tags" (lower case) instead of "Tags" (title case)?

https://github.com/MunifTanjim/minimo/blob/9db19f947a2571801b8e03cb97c6b7fa91c90506/layouts/partials/header/header.html#L13

This one is for taxonomy cloud page (e.g.: at `/tags` or `/categories` url). The title comes from `/i18n/<language-code>.toml` file. So, you will have to override those file and change them there. Or override the template file.

https://github.com/MunifTanjim/minimo/blob/9db19f947a2571801b8e03cb97c6b7fa91c90506/layouts/partials/widgets/taxonomy_cloud.html#L14

This one is for sidebar. Change the value of `taxonomy_cloud.title` in the `/data/config/widgets.toml` file. Or just override the template file.

---

If you are not familiar with overriding theme files, here's how it works:

- Suppose you want to override `/themes/minimo/layouts/path/to/file.html`
- Create a file `/layouts/path/to/file.html`.
- That's it. Now Hugo will use `/layouts/path/to/file.html` instead of `/themes/minimo/layouts/path/to/file.html`

**Comment by jas-ho** [comment]
thanks so much. this is extremely helpful!

the only thing I could not get to work was the title of the page at /tags:
> This one is for taxonomy cloud page (e.g.: at /tags or /categories url). The title comes from /i18n/<language-code>.toml file.

I created a custom file at i18n/en.toml with the following entry:

>[tag]
one = "tag"
other = "tags"

but this did not change anything. any ideas?

**Comment by MunifTanjim** [comment]
Did you updated to the latest commit 9db19f9 ? @jas-ho

**Comment by jas-ho** [comment]
That was exactly the problem. I was using engimo which is based on a less recent version of minimo. Switching to the latest version of minimo fixed it. Thanks so much for your help!!
