### ISSUE TITLE
Syntax highlighting help for .Rmd files

### ISSUE THREAD

**Issue by raheems** [MunifTanjim/minimo#184]
Currently, syntax highlighting works for .md files. I have some files with .Rmd extension and I would like them to be highlighted as well. 

Would you please point me where I will have to make changes so that .Rmd files can have syntax highlighted?

Thanks in advance.

**Comment by MunifTanjim** [comment]
Use [highlight.js](https://highlightjs.org/) or some other frontend syntax highlighter.

**Comment by pat-s** [comment]
Put this 

```html
<link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/tomorrow-night-eighties.min.css" rel="stylesheet">

<script src="////cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script src="////cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>

<script>
hljs.configure({languages: []});
hljs.initHighlightingOnLoad();
</script>
```

in `layouts/partials/footer/extra.html`. You can choose your favorite highlighting theme by replacing `tomorrow-night-eighties` in the example.

Note that you should also disable the default Hugo highlighting in `config.toml` as otherwise the highlighting methods will conflict for .md files.
