### ISSUE TITLE
Pull requests are ignored?

### ISSUE THREAD

**Issue by rvalitov** [MunifTanjim/minimo#274]
Hi! There are some nice pull requests that are waiting over a year to be merged. Does it mean that contribution to this project is not welcome and appreciated? I have a few things I'd like to submit, but when I see that the pull requests are ignored, there's no desire to submit anything.

Any comments from the maintainers is much appreciated to understand their point of view.
Thank you!

**Comment by MunifTanjim** [comment]
The ignored pull requests are mainly for additional icons. I didn't want to put icons of different styles together in this theme, that's why they are not merged yet. The proper thing would be to resolve the #248 (switch to Simple Icons).

> Does it mean that contribution to this project is not welcome and appreciated?

I'm sorry that it seemed that way to you.

But, making that assumption is not right. There are other fixes and features, that are not related to icons, being merged. And I know there are a few other pending stuffs. I haven't got around to review those yet (e.g. #266). I intend to merge those as soon as I can.

> I have a few things I'd like to submit, but when I see that the pull requests are ignored, there's no desire to submit anything.

Maybe you can open an issue about those first, instead of directly creating a PR? Discussing about something before starting to implement it often helps.

**Comment by rvalitov** [comment]
Thank you very much for a prompt response and clear explanation! Because I feel confused when I see pull requests that are pending about a year and have no comments from the maintainer. So it was unclear for me what you think about that and why they are not accepted to be merged and not declined. 

Now I understand you point of view, thank you! And I will create an issue first for discussion before proposing any actual merge requests. I guess this issue can be closed.
