### ISSUE TITLE
question: CSS vendor prefixes

### ISSUE THREAD

**Issue by inet56** [MunifTanjim/minimo#316]
Is there a option not to have any vendor prefixes in served CSS?

**Comment by MunifTanjim** [comment]
You'll need to
- fork this repo
- remove [`autoprefixer` from webpack config](https://github.com/MunifTanjim/minimo/blob/21d3174839536ff63324660ecfc3f4043628ce8f/webpack.config.js#L78)
- run `npm run build` and commit the changes
- use your forked repo instead of `MunifTanjim/minimo` as your Hugo theme

**Comment by inet56** [comment]
Is adding vendor prefixes a good thing to do?
